<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="74918" started-at="2017-01-27T11:08:42Z" finished-at="2017-01-27T11:09:57Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="74918" started-at="2017-01-27T11:08:42Z" finished-at="2017-01-27T11:09:57Z">
      <class name="day_1.Session2">
        <test-method status="PASS" signature="facebook()[pri:0, instance:day_1.Session2@64bf091d]" name="facebook" duration-ms="42518" started-at="2017-01-27T16:38:43Z" finished-at="2017-01-27T16:39:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- facebook -->
        <test-method status="PASS" signature="facebook1()[pri:0, instance:day_1.Session2@64bf091d]" name="facebook1" duration-ms="32335" started-at="2017-01-27T16:39:25Z" finished-at="2017-01-27T16:39:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- facebook1 -->
      </class> <!-- day_1.Session2 -->
      <class name="day_1.Session1">
        <test-method status="FAIL" signature="AasserionsTest()[pri:0, instance:day_1.Session1@29b00e45]" name="AasserionsTest" duration-ms="27827" started-at="2017-01-27T16:38:43Z" finished-at="2017-01-27T16:39:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Iam done with Assertions expected [Demo Windows for practicing Selenium Automation1] but found [Demo Windows for practicing Selenium Automation]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Iam done with Assertions expected [Demo Windows for practicing Selenium Automation1] but found [Demo Windows for practicing Selenium Automation]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at day_1.Session1.AasserionsTest(Session1.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AasserionsTest -->
        <test-method status="PASS" signature="test2()[pri:0, instance:day_1.Session1@29b00e45]" name="test2" duration-ms="28435" started-at="2017-01-27T16:39:10Z" finished-at="2017-01-27T16:39:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
      </class> <!-- day_1.Session1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
